version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.local
    environment:
      - CODEIGNITER_PROJECT_NAME=app
    ports:
      - '8000'
    depends_on:
      - mariadb
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
